name: Deployment Event ftp

on:
  push:
    branches:
      - gh-pages
jobs:
  my-event:
    if: contains(github.actor, 'actions-gh-pages')
    runs-on: ubuntu-20.04
    steps:
    - uses: actions/checkout@v2
    - name: FTP Deploy update
      uses: SamKirkland/FTP-Deploy-Action@4.3.3
      with:
        ftp-server: ${{ secrets.FTP_SERVER }}
        ftp-username: ${{ secrets.FTP_USERNAME }}
        ftp-password: ${{ secrets.FTP_PASSWORD }}
