name: Deployment Event
on:
  push:
    branches:
      - gh-pages
  pull_request:
    branches:
      - gh-pages
  issues:
    types:
      - opened
      - closed
      - edited
    branches:
      - gh-pages
    repository_dispatch:
      types: [gh-pages-updated]
jobs:
  deploy:
    name: Deploy ftp
    runs-on: ubuntu-20.04
    steps:
    - uses: actions/checkout@v2
    - name: FTP Deploy update
      uses: SamKirkland/FTP-Deploy-Action@3.1.2
      with:
        ftp-server: ${{ secrets.FTP_SERVER }}
        ftp-username: ${{ secrets.FTP_USERNAME }}
        ftp-password: ${{ secrets.FTP_PASSWORD }}
