name: Deploy via ftp
on: push
jobs:
  deploy:
    name: Deploy
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: FTP Deploy update
      uses: SamKirkland/FTP-Deploy-Action@3.1.2

      with:
        ftp-server: ${{ secrets.FTP_SERVER }}
        user: ${{ secrets.FTP_USERNAME }}
        password: ${{ secrets.FTP_PASSWORD }}
        ftp-port: 21
        localDir: "./public"
        remoteDir: "www"
