name: Build and Deploy

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    

    steps:
    - name: Checkout code
      uses: actions/checkout@v3
    - name: Setup Node.js
      uses: actions/setup-node@v3
      with:
        node-version: 16

    - name: Install dependencies
      run: npm ci

    - name: Build
      run: npm run build

    - name: Deploy
      run: |
        git config --global user.email "victorbasso36@gmail.com"
        git config --global user.name "VictorBasso36"
        git remote set-url origin https://x-access-token:${{ secrets.GITHUB_TOKEN }}@github.com/${{ github.repository }}.git
        git push --set-upstream origin ProducaoBranch
        git add -f build
        git add .
        git commit -m "Deploy"
        git push -f origin ProducaoBranch
        

